### PR TITLE
Issue 6: Add support for ini file to be able to run unit_tests in dev

### PR DESCRIPTION
**Pull request by progier389**
Issue 6: Add support for ini file to be able to run unit_tests in dev environment

add support for ini file
also improved makefile to add a pylint pass
 Note: I did not yet tried to fix the plugins modules to be fully pylint error free (will be done in another issue)
    but at least there is no more any warning in  the test framework: 

```
cd ansible_collections/ds/ansible_ds/tests; pylint --max-line-length=130 '--ignore-long-lines=^\s.*Option.*$' --method-naming-style=camelCase $(find . -name '*.py')

------------------------------------
Your code has been rated at 10.00/10
```
Reviewd by: 

issue: #6

### CODE REVIEW

**Review by droideck — COMMENTED** [review]
Also, on a clean machine I have the next error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib64/python3.10/configparser.py", line 790, in get
INTERNALERROR>     value = d[option]
INTERNALERROR>   File "/usr/lib64/python3.10/collections/__init__.py", line 986, in __getitem__
INTERNALERROR>     return self.__missing__(key)            # support subclasses that define __missing__
INTERNALERROR>   File "/usr/lib64/python3.10/collections/__init__.py", line 978, in __missing__
INTERNALERROR>     raise KeyError(key)
INTERNALERROR> KeyError: 'prefix'
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/mnt/tests/rhds/tests/upstream/ansible-ds/ansible_collections/ds/ansible_ds/tests/conftest.py", line 185, in pytest_sessionstart
INTERNALERROR>     _CONFIG.exportAll()
INTERNALERROR>   File "/mnt/tests/rhds/tests/upstream/ansible-ds/ansible_collections/ds/ansible_ds/tests/conftest.py", line 65, in exportAll
INTERNALERROR>     val = self.config.get(self.best_section, var)
INTERNALERROR>   File "/usr/lib64/python3.10/configparser.py", line 793, in get
INTERNALERROR>     raise NoOptionError(option, section)
INTERNALERROR> configparser.NoOptionError: No option 'prefix' in section: '/'
```

I'll look deeper tomorrow.

**Comment by progier389** [comment]
Thanks for the comments @droideck ! 
FYI: I changed the Makefile as you suggested and fixed the NoOptionError exception in the last commit.

**Comment by droideck** [comment]
I've noticed another strange error.
When I run the ansible-playbook the first time, it gives me the next error:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "INFO: Starting installation ...\nINFO: Validate installation settings ...\nINFO: Create file system structures ...\nINFO: Create self-signed certificate database ...\nINFO: Perform SELinux labeling ...\nINFO: Perform post-installation tasks ...\nINFO: Completed installation for instance: slapd-ansible-default\n",
    "module_stdout": "[general]\nversion = 2\nstart = True\n\n[slapd]\ninstance_name = ansible-default\nroot_password = 3uQ!PvwGfZ-yWNKEqQ!gZsPtv\nport = 33825\nsecure_port = 37255\nself_sign_cert = True\n\n\n{\"changed\": false, \"original_message\": \"\", \"message\": \"goodbye\", \"my_useful_info\": {\"tag\": \"!ds389Host\", \"name\": \"ci-vm-10-0-136-121.hosted.upshift.rdu2.redhat.com\", \"state\": \"present\", \"instances\": {\"supplier2\": {\"tag\": \"!ds389Instance\", \"name\": \"supplier2\", \"state\": \"present\", \"backends\": {\"userroot\": {\"tag\": \"!ds389Backend\", \"name\": \"userroot\", \"state\": \"present\", \"require_index\": \"off\", \"suffix\": \"dc=example,dc=com\"}}, \"started\": true, \"dseMods\": {\"tag\": \"tag:yaml.org,2002:map\", \"cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"deleteValue\": {\"tag\": \"tag:yaml.org,2002:map\", \"nsslapd-security\": [null]}}, \"cn=encryption,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"deleteValue\": {\"tag\": \"tag:yaml.org,2002:map\", \"CACertExtractFile\": [null]}}, \"cn=rfc 2829 u syntax,cn=mapping,cn=sasl,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"addEntry\": {\"tag\": \"tag:yaml.org,2002:map\", \"objectClass\": [\"top\", \"nsSaslMapping\"], \"cn\": [\"rfc 2829 u syntax\"], \"nsSaslMapRegexString\": [\"^u:\\\\(.*\\\\)\"], \"nsSaslMapBaseDNTemplate\": [\"dc=example,dc=com\"], \"nsSaslMapFilterTemplate\": [\"(uid=\\\\1)\"]}}, \"cn=uid mapping,cn=mapping,cn=sasl,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"addEntry\": {\"tag\": \"tag:yaml.org,2002:map\", \"objectClass\": [\"top\", \"nsSaslMapping\"], \"cn\": [\"uid mapping\"], \"nsSaslMapRegexString\": [\"^[^:@]+$\"], \"nsSaslMapBaseDNTemplate\": [\"dc=example,dc=com\"], \"nsSaslMapFilterTemplate\": [\"(uid=&)\"]}}}, \"port\": \"39002\", \"secure_port\": \"63702\", \"nsslapd_directory\": \"/var/lib/dirsrv/slapd-supplier2/db\"}, \"localhost\": {\"tag\": \"!ds389Instance\", \"name\": \"localhost\", \"state\": \"present\", \"started\": true, \"dseMods\": {\"tag\": \"tag:yaml.org,2002:map\", \"cn=entryuuid task,cn=tasks,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"deleteEntry\": {\"tag\": \"tag:yaml.org,2002:map\", \"fullRemoval\": [true]}}}, \"port\": \"389\", \"secure_port\": \"636\", \"nsslapd_directory\": \"/var/lib/dirsrv/slapd-localhost/db\"}, \"supplier1\": {\"tag\": \"!ds389Instance\", \"name\": \"supplier1\", \"state\": \"present\", \"backends\": {\"userroot\": {\"tag\": \"!ds389Backend\", \"name\": \"userroot\", \"state\": \"present\", \"require_index\": \"off\", \"suffix\": \"dc=example,dc=com\"}}, \"started\": true, \"dseMods\": {\"tag\": \"tag:yaml.org,2002:map\", \"cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"deleteValue\": {\"tag\": \"tag:yaml.org,2002:map\", \"nsslapd-security\": [null]}}, \"cn=encryption,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"deleteValue\": {\"tag\": \"tag:yaml.org,2002:map\", \"CACertExtractFile\": [null]}}, \"cn=rfc 2829 u syntax,cn=mapping,cn=sasl,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"addEntry\": {\"tag\": \"tag:yaml.org,2002:map\", \"objectClass\": [\"top\", \"nsSaslMapping\"], \"cn\": [\"rfc 2829 u syntax\"], \"nsSaslMapRegexString\": [\"^u:\\\\(.*\\\\)\"], \"nsSaslMapBaseDNTemplate\": [\"dc=example,dc=com\"], \"nsSaslMapFilterTemplate\": [\"(uid=\\\\1)\"]}}, \"cn=uid mapping,cn=mapping,cn=sasl,cn=config\": {\"tag\": \"tag:yaml.org,2002:map\", \"addEntry\": {\"tag\": \"tag:yaml.org,2002:map\", \"objectClass\": [\"top\", \"nsSaslMapping\"], \"cn\": [\"uid mapping\"], \"nsSaslMapRegexString\": [\"^[^:@]+$\"], \"nsSaslMapBaseDNTemplate\": [\"dc=example,dc=com\"], \"nsSaslMapFilterTemplate\": [\"(uid=&)\"]}}}, \"port\": \"39001\", \"secure_port\": \"63701\", \"nsslapd_directory\": \"/var/lib/dirsrv/slapd-supplier1/db\"}}, \"prefix\": \"\"}, \"invocation\": {\"module_args\": {\"prefix\": \"\"}}}\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}
```

When I run it the second time - everything is good.
So I wonder if there's something wrong with installation return codes...

**Comment by progier389** [comment]
That is weird indeed, that said I doubt it is related to return code (There is no such notion in Ansible module API
 (cf  run_module function in ds_info.py: Either we get an exception and the message will be different
   or we send back the result dict ... )
 As module_stderr and module_stdout are not in our code, I suspect it is computed by the role calls the module 
Maybe it is simply because stderr is not empty ...
That said, I  did not reproduce the issue even after rm /etc/dirsrv/dse-ansible-default.ldif so ether is is ansible version dependant or the problem is else where
FYI: while I was doing  my test I found an issue with playbook if thee are no DS instances, that I  fixed in last commit

**Review by droideck — APPROVED** [review]
Yeah, it's really confusing. I'll keep searching but I don't want to keep this PR from merging.
This looks really good! Ack from me:)

**Pull request merged**
