### PR TITLE
Issue 28 - Fix Ansible lint issues - Backup Role and Playbooks

### PR DESCRIPTION
**Pull request by droideck**
Description: Address the issues in the existing backup role and playbooks. Add .ansible-lint file and except command/shell-related errors as they are not relevant to the way we do things.

Relates: https://github.com/389ds/ansible-ds/issues/28

Reviewed by: ?

### CODE REVIEW

**Review by progier389 — APPROVED** [review]
LGTM. I wonder about the skip list but lets use it for now, it will always be time to see if we find a way to remove some of them later

**Comment by progier389** [comment]
BTW: I still see some backup related errors in  ansible lint test output

**Comment by droideck** [comment]
I'll put Work in Progress for now, as I still need to tweak the lint config and yep, a couple more errors were missed (not exception related).

**Comment by droideck** [comment]
@progier389 all of the "backup task" issues were cleaned up. Feel free to recheck! Thanks!

**Comment by droideck** [comment]
@progier389 all of the "backup task" issues were cleaned up. Feel free to recheck! Thanks!

**Comment by progier389** [comment]
Nice ! The test results are clean now. I will wait before fixing the instance creation playbooks because addimg the action plugin will likely have an impact!

**Pull request merged**
