### PR TITLE
Issue 31 - Sync code with plugin and module design

### PR DESCRIPTION
**Pull request by progier389**
Changes:
- Run ansible-lint on top of git repository instead of within ~/.ansible (so the tests and the galaxy framework are tested)
- Fixed github action so that lint is run with the PR build.
- Fixed ansible-lint errors ( Added changelog and meta file)
- Merged the 2 modules in a single ds389_module module
- Fixed the ds38_server action plugin to handle the replicated topology inventory and be able to:
   - handle the ds389_option_xxx merge/append request
   - resolve the ds389_agmts agreements (by merging the targed backend parameters in the agreement)  
- Fixed the ds389_module to accept the parameters sent by ds389_server action plugin
- Added ds389_info action plugin and its test case
- Added extra test (and update the design document) about the topology consistency in the action plugin
    (because that is the only place were the whole topology is found) to check:
       - that replica id is unique for a given suffix among the topology
       - high level consistency about replica role and the parameters (only suppliers have a replicaid / consumer must not have agreements) (low level consistency should be handled within the module) 

Still need to be done: 
- Add the doc metadata inside the  module
 - Fixing bug in the module and adding the missing code so that:
    -  replica, replication manager entry,  and agreement are rightly created.
    -  update state works properly at backend/ index/ replica /agmt levels

Issue: [31](https://github.com/389ds/ansible-ds/issues/31)

Reviewed by: @droideck (Thanks!)

### CODE REVIEW

**Review by droideck — APPROVED** [review]
The code looks good!

I see that some tests are skipped:

- Pytests (inventory/basic/test_basic_inventory.yml) 
- Pytests (inventory/replication/test_replication_inventory.yml)
- Pytests (playbooks/test_ds389_create.yml)
- Pytests (playbooks/test_ds389_remove.yml)
- Pytests (playbooks/test_gather_dsinst_info.yml)

Was it intentional, I guess? (as you said you plan to bring more PRs along with this PR work in your next PR)

**Comment by progier389** [comment]
Good catch. No it is not intended
Looks like all the yaml tests are skipped on github 
Interestingly that is not the case when I run make unit_test on my machine. 
I think that the only skip directive is in conftest, I will try to fix it.

**Comment by progier389** [comment]
Fixed the skipped issue ( was due to the fact that the collection tar file was not found on the test containers (because collection is not built on these container)
Now it works but the inventory tests are still failing ( This time it is an issue when setting up docker instance with ansible I will look at it)
```
TASK [Create docker network Test389ds] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"}
```

**Comment by progier389** [comment]
The issue is that docker is not available from within a docker container. Adding a test in conftest to skip the inventory tests  if docker is not available. We should think later on if there is a way to creates the four docker instances within github actions (Not sure we can do that without using self hosted runners)

**Pull request merged**
